options:
  access-key:
    description: |
      An IAM access key.

      It is strongly recommended that you use `juju trust` instead, if available.
    type: string
    default: ""
  secret-key:
    description: |
      An IAM secret key.

      It is strongly recommended that you use `juju trust` instead, if available.
    type: string
    default: ""
